### ISSUE TITLE
Create a future that immediately resolves to an exception

### ISSUE THREAD

**Issue by michal-grzejszczak** [fresheneesz/asyncFuture#2]
Sometimes in potentially synchronous functions I want to return the future immediately with an exception. I can create a future with a resolved value in one line

```
new Future('blah')
```

but it would be handy to have a version that can be initialized to a state that causes catch functions to be called. Right now I have to write something like:

```
var f  = new Future()
f.throw(some_error)
return f
```

Had `throw` return the future instead of nothing I could write:

```
return new Future().throw(some_error)
```

Is there a better way to handle this?

**Comment by fresheneesz** [comment]
I have that pattern in my code too.  I could have throw return the future, not a big deal there.

**Comment by fresheneesz** [comment]
Ok v1.0.6 published on npm with that change for ya
